# CodeRabbit Configuration for FarmSmart AI
# This file configures how CodeRabbit reviews your code for the FarmSmart AI project

# Reviews Configuration
reviews:
  path_filters:
    - "**/*.{js,jsx,ts,tsx}"
    - "**/*.{json,yml,yaml}"
    - "**/*.{md,txt}"
    - "**/*.{css,scss}"
    - "**/*.config.{js,ts}"
    - "**/*.d.ts"
    - "!node_modules/**"
    - "!.next/**"
    - "!dist/**"
    - "!build/**"
    - "!*.log"
    - "!.env*"
    - "!package-lock.json"
    - "!yarn.lock"
    - "!pnpm-lock.yaml"
    - "!*.tsbuildinfo"
    - "!next-env.d.ts"
    - "!public/**"
    - "!.git/**"

  path_instructions:
    - path: "**/*.tsx"
      instructions: "Check for TypeScript types, accessibility attributes, React hooks rules, and 'use client' directive when needed"
    - path: "src/app/api/**/*.ts"
      instructions: "Verify error handling, input validation, API key security, and proper HTTP status codes"
    - path: "**/*.css"
      instructions: "Ensure Tailwind classes are used, no inline styles, responsive design included"
    - path: "**/plant-scanner/**"
      instructions: "Check Plant.id API integration, error handling for failed scans, image processing"
    - path: "**/ai-measure/**"
      instructions: "Verify Google Vision API usage, measurement accuracy, error boundaries"
    - path: "src/contexts/ThemeContext.tsx"
      instructions: "Ensure theme persistence works, check for hydration issues, verify localStorage usage"
    - path: "src/components/Sidebar.tsx"
      instructions: "Test mobile responsiveness, verify theme toggle functionality, check navigation accessibility"
    - path: "src/components/Layout.tsx"
      instructions: "Ensure proper responsive behavior, test theme integration, verify accessibility"

  labeling_instructions:
    - label: "security"
      instructions: "Apply when changes involve API keys, authentication, or user input validation"
    - label: "performance"
      instructions: "Apply when changes affect bundle size, API calls, or rendering"
    - label: "accessibility"
      instructions: "Apply when changes affect keyboard navigation, ARIA attributes, or screen readers"
    - label: "api-integration"
      instructions: "Apply for Plant.id or Google Vision API changes"
    - label: "theme-system"
      instructions: "Apply when changes affect dark mode, theme context, or styling"
    - label: "react-best-practices"
      instructions: "Apply for React hooks, component patterns, or state management changes"
    - label: "typescript"
      instructions: "Apply for type safety, interfaces, or TypeScript-specific changes"
    - label: "tailwind"
      instructions: "Apply for styling, responsive design, or CSS utility classes"

# Tools Configuration
tools:
  # Code Quality Tools
  eslint:
    enabled: true
    config_file: "eslint.config.mjs"

  # Security Tools
  security_scan:
    enabled: true
    tools:
      - "npm audit"
      - "snyk"

  # Bundle Analysis
  bundle_analyzer:
    enabled: true
    threshold: 500000 # 500KB gzipped

# Knowledge Base Configuration
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "README.md"
      - "CONTRIBUTING.md"
      - "docs/**/*.md"
    sources:
      - "Plant.id API documentation"
      - "Google Vision API documentation"
      - "Next.js 14+ documentation"
    topics:
      - "TypeScript best practices"
      - "React best practices"
      - "Next.js 14+ patterns"
      - "Tailwind CSS conventions"
      - "Accessibility guidelines"
      - "Security best practices"
    patterns:
      - "App Router structure"
      - "Component composition"
      - "API route patterns"
      - "State management"
      - "Theme system"

  learnings:
    enabled: true
    files:
      - "src/components/Sidebar.tsx"
      - "src/contexts/ThemeContext.tsx"
      - "src/app/api/plant-scan/route.ts"
      - "src/app/page.tsx" 